### ISSUE TITLE
Pipes not working in @actions/exec node module

### ISSUE THREAD

**Issue by Kerizer** [actions/toolkit#359] opened 2020-02-20 08:23 UTC
**Describe the bug**
It looks like @actions/exec.exec escapes commands and pipes are not working because of this

**To Reproduce**
1. Create a new javascript action
2. Add `@actions/exec` to project - `npm i -s @actions/exec`
3. In your index file add any .exec command with pipe, ie: `echo "Hello world" | grep "o"`
4. It would print `Hello world" | grep "o"`, instead of `Hell**o** w**o**rld` (asterisks here are only for visual purpose, i do not expect them to be in log)
![Screenshot 2020-02-20 at 10 22 40](https://user-images.githubusercontent.com/21887713/74914468-2a37fc00-53cb-11ea-9414-d0a4d4d717a4.png)

**Expected behavior**
Have an option to disable escaping

**Screenshots**
![image](https://user-images.githubusercontent.com/21887713/74913646-bfd28c00-53c9-11ea-92af-a8764ee37829.png)

**Desktop (please complete the following information):**
 - OS: tested on macOS-latest machine
 - Version @actions/exec@1.0.3

**Comment by hrueger** [comment] 2020-03-24 07:06
@Kerizer I have the same problem, the command I want to run is `yes | sdkmanager --licenses` to automatically accept all prompts with `yes`. This does not work, it takes `| sdkmanager --licenses` as one argument and prints that forever until I cancel the workflow.

A workaround I found is to use `/bin/bash -c "my command"` , e.g. `/bin/bash -c "yes | sdkmanager --licenses"`. That worked for me.

**Comment by hrueger** [comment] 2020-03-25 03:08
As I just found out, this also affects chaning commands with `&&`...

**Comment by rickstaa** [comment] 2020-12-12 12:46
@hrueger Thanks a lot for the workaround. For future reference here is the windows equivalent:

**WINDOWS**:

```python
exec.exec(`cmd /c "my command"`)
```

**Comment by thboop** [comment] 2021-04-29 18:35
Closing as a dupe of https://github.com/actions/toolkit/issues/346

**Closed by thboop** 2021-04-29 18:35 UTC
Labels: bug
