### ISSUE TITLE
Problem matcher fromPath documentation

### ISSUE THREAD

**Issue by xt0rted** [actions/toolkit#480] opened 2020-05-27 04:55 UTC
There's not much in the [problem matcher docs](https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md) about the `fromPath` field. I'm trying to use it on the following output:

```
Run dotnet format --workspace src/Application.sln --dry-run
  dotnet format --workspace src/Application.sln --dry-run
  shell: /bin/bash -e {0}
  Formatting code files in workspace '/home/runner/work/actions-playground/actions-playground/src/Application.sln'.
  ConsoleApp1/Program.cs(4,22): Fix whitespace formatting.
  ConsoleApp1/Program.cs(6,3): Fix whitespace formatting.
  ConsoleApp1/Program.cs(7,21): Fix whitespace formatting.
  Formatted code file 'Program.cs'.
  Format complete in 5063ms.
```

This is my problem matcher:

```json
{
  "problemMatcher": [
    {
      "owner": "dotnet-format",
      "pattern": [
        {
          "regexp": "^\\s+Formatting code files in workspace '(.*)[\\\\/].*\\.sln'\\.$",
          "fromPath": 1
        },
        {
          "regexp": "^\\s+(.*)\\((\\d+),(\\d+)\\):\\s+(.*)$",
          "file": 1,
          "line": 2,
          "column": 3,
          "message": 4,
          "loop": true
        }
      ]
    }
  ]
}
```

The issue I'm having is on `ubuntu-latest` it matches the first line with the solution file, matches each error and highlighting them, but no annotations are created. This is the output with debugging enabled:

```
  Formatting code files in workspace '/home/runner/work/actions-playground/actions-playground/src/Application.sln'.
##[debug]Dropping file value '/home/runner/work/actions-playground/actions-playground/ConsoleApp1/Program.cs'. Path does not exist
##[error]  ConsoleApp1/Program.cs(4,22): Fix whitespace formatting.
##[debug]Dropping file value '/home/runner/work/actions-playground/actions-playground/ConsoleApp1/Program.cs'. Path does not exist
##[error]  ConsoleApp1/Program.cs(6,3): Fix whitespace formatting.
##[debug]Dropping file value '/home/runner/work/actions-playground/actions-playground/ConsoleApp1/Program.cs'. Path does not exist
##[error]  ConsoleApp1/Program.cs(7,21): Fix whitespace formatting.
  Formatted code file 'Program.cs'.
  Format complete in 5280ms.
```

I'd expect the matched path to be
```
/home/runner/work/actions-playground/actions-playground/src/ConsoleApp1/Program.cs
```
instead of
```
/home/runner/work/actions-playground/actions-playground/ConsoleApp1/Program.cs
```

Is this setup supported where the first regex matches the `fromPath` and the second matches the file & error details? If this isn't supported is there some way to make this work?

**Comment by xt0rted** [comment] 2020-05-27 06:27
After digging through the runner code I came across this https://github.com/actions/runner/blob/11435857e4cd9795fa5ee68c20b674e5f96052ab/src/Runner.Worker/Handlers/OutputManager.cs#L266-L273. Based on that I changed my first regex to include the project file name in the match and now the annotations are being created correctly. Including some more info on this in the docs would be nice.

**Comment by thboop** [comment] 2021-04-29 19:39
dupe of https://github.com/actions/toolkit/issues/394

**Closed by thboop** 2021-04-29 19:39 UTC
