### ISSUE TITLE
Don't create checks on issues

### ISSUE THREAD

**Issue by estrada9166** [actions/toolkit#86] opened 2019-08-26 18:40 UTC
How can I enable the action only to run when an issue is created without setting checks... If my base branch is develop, and I have PR opened to master, every time an issue is created it's gonna assign checks to my PR. something that I don't want because the action is only used to assign users to it, no to prevent merging a PR.

how can I prevent this behavior?

**Comment by gimenete** [comment] 2019-08-28 15:50
@damccorm I'll create an internal issue. The problem is that when an event not related to a push triggers Actions, Actions searches the latest version of the workflow files. In order to do that it uses the latest commit in the default branch. This makes sense in order to decide which version of the workflow file is used. Then checks are created and the SHA is stored in them. These checks need to be created to show up in the Actions tab and be able to debug anything.

However that SHA used to find the right workflow file version may also be the latest SHA in a PR, which causes the checks to appear in the merge box (and probably other places of the UI) and this is what's happening here, which is confusing to the users.

**Comment by bryanmacfarlane** [comment] 2019-09-17 13:12
Closing here since not toolkit related and tracking internally

**Closed by bryanmacfarlane** 2019-09-17 13:12 UTC
Labels: external

**Comment by gimenete** [comment] 2019-09-24 16:16
We have shipped a fix for this. Here's a blog post with more information https://github.blog/changelog/2019-09-24-ui-changes-in-github-actions-checks/
